version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./html/site1:/var/www/html/site1
      - ./html/site2:/var/www/html/site2
      - ./html/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - site1_php
      - site2_php
      - site3_python
  site1_php:
    image: php:5.6-fpm-alpine
    volumes:
      - ./html/site1:/var/www/html/site1
  site2_php:
    image: php:8.2.4-fpm
    volumes:
      - ./html/site2:/var/www/html/site2
  site3_python:
    build:
      context: ./html/site3
      dockerfile: Dockerfile
    volumes:
      - ./html/site3:/app
